import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Row, Col } from 'react-bootstrap';
import { FaMapMarkerAlt, FaClock, FaCommentDots, FaPhoneAlt } from 'react-icons/fa';
import ContactForm from './ContactForm';
import WhyChooseUs from './WhyChooseUs';
import IrrigationServices from './IrrigationServices';
const Hero = () => {
    return (_jsx("section", { id: "hero", children: _jsxs("div", { className: "container py-5", children: [_jsxs(Row, { children: [_jsxs(Col, { md: 6, className: "d-flex flex-column justify-content-start", children: [_jsx("div", { className: "mb-4 flex align-items-center", children: _jsxs("div", { className: "mb-4 d-flex align-items-center", children: [_jsx("img", { decoding: "async", width: "50", height: "50", className: "wp-image-1339", style: { width: '50px' }, src: "images/leaf-irrigation.png", alt: "" }), _jsx("p", { className: "highlight-blue mb-0 ms-3", style: { color: '#BCBA63' }, children: "A Garden Like Never Before" })] }) }), _jsx("h2", { className: "fw-bold", style: { fontSize: '4rem', fontWeight: 700 }, children: "Pacific Northwest Irrigation" }), _jsxs("p", { className: "lead mt-3 lead-on-green", children: [_jsx("span", { className: "highlight-blue", children: "At Pacific Northwest Irrigation" }), ", we specialize in designing, installing, and maintaining efficient, eco-friendly irrigation systems tailored to the unique needs of the Pacific Northwest, backed by years of expertise in sustainable water management."] }), _jsxs("div", { className: "mt-4  align-items-center ", style: {
                                        backgroundImage: "url('images/watering-garden.jpg')",
                                        padding: "10px 20px 30px 20px",
                                        borderRadius: "10px", backgroundSize: "cover", backgroundPosition: "center"
                                    }, children: [_jsx("img", { decoding: "async", width: "50", height: "50", className: "wp-image-1339", style: { width: '50px' }, src: "images/seeding.png", alt: "Seeding Icon" }), _jsx("h2", { style: { margin: '10px 0 35px 0' }, children: "Transforming Your Outdoor Oasis with Precision" }), _jsxs("p", { children: ["Expert ", _jsx("a", { href: "/irrigation-services", className: "fs-4 fw-bold", style: { color: '#007bff', textDecoration: 'none', marginTop: '20px' }, children: "irrigation solutions" }), " designed to nurture your landscape, conserve resources, and enhance the beauty of your outdoor spaces."] })] })] }), _jsx(Col, { md: 6, children: _jsxs("div", { className: "bg-light bg-opacity-75 text-dark p-4 rounded", children: [_jsx("h2", { className: "text-success mb-4", children: "Contact Us" }), _jsx(ContactForm, {}), _jsxs("div", { className: "mt-4", children: [_jsxs("p", { children: [_jsx(FaCommentDots, { className: "me-2 text-danger" }), "Here\u2019s how you can contact us for any questions or concerns:"] }), _jsxs("p", { children: [_jsx(FaMapMarkerAlt, { className: "me-2 text-primary" }), "2360 Hood Avenue, San Diego, CA, 92123"] }), _jsxs("p", { children: [_jsx(FaClock, { className: "me-2 text-primary" }), "08:00 AM \u2013 04:00 PM"] }), _jsxs("p", { children: [_jsx(FaPhoneAlt, { className: "me-2 text-primary" }), "+1 334 422 2211"] })] })] }) })] }), _jsx(Row, { children: _jsx(Col, { className: "text-center mt-5", children: _jsx(WhyChooseUs, {}) }) }), _jsx(Row, { children: _jsx(Col, { className: "text-center mt-5", children: _jsx(IrrigationServices, {}) }) })] }) }));
};
export default Hero;
